FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

WORKDIR /workspace
COPY . .

RUN go build -gcflags="all=-N -l" -o order ./cmd/main.go

FROM golang:1.21-alpine

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /workspace
COPY --from=builder /workspace/order .

EXPOSE 8080 2346

CMD ["/go/bin/dlv", "--listen=:2346", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./order"]