kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
  extraMounts:
  - hostPath: /workspace
    containerPath: /workspace
- role: worker
  extraMounts:
  - hostPath: /workspace
    containerPath: /workspace
- role: worker
  extraMounts:
  - hostPath: /workspace
    containerPath: /workspace