# skaffold.debug.yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: p5gsi-debug
build:
  artifacts:
  - image: user
    context: user
    docker:
      dockerfile: Dockerfile.debug
    sync:
      manual:
      - src: 'user/**'
        dest: .
  - image: order
    context: order
    docker:
      dockerfile: Dockerfile.debug
    sync:
      manual:
      - src: 'order/**'
        dest: .
manifests:
  kustomize:
    paths:
    - manifest/user/overlays/dev
    - manifest/order/overlays/dev
deploy:
  kubectl: {}
  statusCheckDeadlineSeconds: 300
portForward:
- resourceType: service
  resourceName: user
  port: 30001
  localPort: 30001
- resourceType: service
  resourceName: user
  port: 2345
  localPort: 2345
- resourceType: service
  resourceName: order
  port: 30002
  localPort: 30002
- resourceType: service
  resourceName: order
  port: 2345
  localPort: 2346