apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 