version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - vscode-extensions:/home/vscode/.vscode-server/extensions
    command: sleep infinity
    privileged: true

volumes:
  vscode-extensions: