apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002
  - name: debug
    port: 2346
    targetPort: 2346
    nodePort: 32346
  selector:
    app: order
