apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: PORT