apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
  - name: debug
    port: 2345
    targetPort: 2345
    nodePort: 32345
  selector:
    app: user
